stages:
  fetch_data:
    cmd: uv run python src/fetch_data.py
    deps:
      - src/fetch_data.py
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/churn.csv
      - src/preprocess.py
    outs:
      - data/processed/churn_cleaned.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/churn_cleaned.csv
      - src/train.py
    params:
      - train
      - model_selection.threshold
