base:
  project: telecom-churn
  random_state: 42

data:
  raw_csv: data/churn.csv
  test_size: 0.2

train:
  n_estimators: 250
  max_depth: 25
  class_weight: "balanced"

model_selection:
  threshold: 0.3